import{i,S as m}from"./assets/vendor-beb23274.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();function p(){const s=h.value.trim().split(",").join("+"),r=new URLSearchParams({key:"42633759-4a44573e34755b4488adb4c1b",q:[s],image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${r}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function u(s){if(s.length==0)i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const r=s.map(e=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${e.largeImageURL}">
            <img class="photo" src="${e.webformatURL}" alt="${e.tags}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${e.likes}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${e.views}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${e.comments}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${e.downloads}</p></li>
            </ul>
            </li>`).join("");a.insertAdjacentHTML("beforeend",r),d.refresh()}}const c=document.querySelector(".search-form"),f='<div class="loader"></div>',h=c.elements.search,a=document.querySelector(".gallery"),d=new m(".gallery a",{captionsData:"alt",captionDelay:250});c.addEventListener("submit",g);function g(s){s.preventDefault(),a.innerHTML="",a.insertAdjacentHTML("beforebegin",f);const r=s.target.elements.search.value.trim();console.log(r),r!==""?(p().then(e=>u(e.hits)).catch(e=>{console.log(e),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}),c.reset()):i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
